### ISSUE TITLE
Automate release chart(s) creation

### ISSUE THREAD

**Issue by vdice** [deis/deisrel#1]
See https://github.com/deis/workflow/blob/master/src/roadmap/release-checklist.md#step-2-create-a-new-helm-chart for the steps needing to be covered.

TODO:

 - [x] https://github.com/deis/deisrel/pull/10
 - [x] https://github.com/deis/deisrel/issues/13

Related to the meta ticket https://github.com/deis/jenkins-jobs/issues/55

**Comment by arschles** [comment]
>Related to the meta ticket #55

@vdice which ticket are you referring to?

**Comment by vdice** [comment]
@arschles description updated w/ proper link -- thanks!

**Comment by vdice** [comment]
Finalized in #13
