### ISSUE TITLE
deisrel doesn't know what to do with these...

### ISSUE THREAD

**Issue by krancour** [deis/deisrel#102]
This is a short, but probably non-exhaustive list of deis repos that deisrel currently lacks any knowledge of. Not all of these repos represent a "component," and further, some are versioned with the rest of Workflow and some are not necessarily. (As a for instance, `docker-go-dev`, has its own progression of releases.) What all of these _do_ have in-common as that, afaik, their labels and milestones are controlled by deis/seed-repo and their issues and PRs are often tagged to a Workflow milestone...

Insofar as https://github.com/deis/deisrel/pull/101 seeks to make bulk reassignment of issues from one milestone to another a possibility, we probably need to figure out how to incorporate each of the following into deisrel. (i.e. The semantics of dealing with repos seems to be different for those containing the source of "components" vs those that that do not. The semantics might be different still for repos that shouldn't be versioned in lock step with Workflow.)

cc @arschles 

* controller-sdk-go
* deisrel
* docker-go-dev
* docker-python-dev
* docker-shell-dev
* e2e-runner
* gutenberg
* jenkins-jobs
* k8s-claimer
* nsq
* object-storage-cli
* seed-repo
* wal-e
* workflow-cli
* workflow-manager-api

**Comment by jchauncey** [comment]
most of those i get. but definitely the nsq and workflow-cli repo seems like it should be handled by deisrel

**Comment by krancour** [comment]
@jchauncey I think they all need to be handled by it in some capacity. For instance, right now I am working on #101 that allows us to move issues between milestones in bulk. It's hard to do that when deisrel doesn't know anything about 1/3 of the repos.

**Comment by arschles** [comment]
Ref https://github.com/deis/deisrel/issues/12 since that issue is for fetching all components & repos from a canonical source, instead of hard-coding as deisrel does now

**Comment by Joshua-Anderson** [comment]
I'm going to close this because deisrel now uses a file for a list repositories rather than a hard coded constant.
