### ISSUE TITLE
Retrieve canonical generate_params.toml via GH API

### ISSUE THREAD

**Issue by vdice** [deis/deisrel#11]
In https://github.com/deis/deisrel/blob/master/actions/generate_params.go and https://github.com/deis/deisrel/blob/master/actions/generate_params_e2e.go we construct local versions of the appropriate `.toml` files, but it would be better to pull the latest canonical versions of each from the [deis/charts](https://github.com/deis/charts.git) repo as these files change.

**Comment by Joshua-Anderson** [comment]
This is no longer relevant as deisrel no longer updates charts.
