### ISSUE TITLE
Make deisrel take a list of components & repos

### ISSUE THREAD

**Issue by arschles** [deis/deisrel#115]
Instead of hard-coding them

**Comment by arschles** [comment]
Removed from v2.2 - we've put deisrel development on hold for the time being until we solidify our release process & tools going forward

**Comment by mboersma** [comment]
Although a lot of `deisrel` functionality has been tossed overboard, I think the existing commands don't hard code component names, and the implementation of #122 uses a local file to know which components to enumerate.
