### ISSUE TITLE
Retrieve canonical list of workflow component/repo names

### ISSUE THREAD

**Issue by vdice** [deis/deisrel#12]
In https://github.com/deis/deisrel/blob/master/actions/common.go we produce a local data structure involving ideally the most up-to-date listing of [Deis Workflow](https://github.com/deis/workflow) component repo names.  It would be preferable to go straight to the canonical source for such information.  

Though this canonical source doesn't quite exist yet, it is envisioned that [Workflow Manager](https://github.com/deis/workflow-manager) will be the likely candidate.

**Comment by Joshua-Anderson** [comment]
Is there still interest in a canonical source? At the moment we've moved to creating a file with all the components we're specifically interested int.

**Comment by jchauncey** [comment]
no i think this is irrelevant now with how we release
