### ISSUE TITLE
deisrel branches create does not perform on additionalGitRepos

### ISSUE THREAD

**Issue by vdice** [deis/deisrel#120]
The `deisrel branches create ...` command appears to only perform on the workflow chart [component repos](https://github.com/deis/deisrel/blob/master/git/repo_names.go#L5-L22) but not the additional, non-workflow chart [component repos](https://github.com/deis/deisrel/blob/master/actions/common.go#L54) such as `(deis/)workflow`, `(deis/)charts` and `(deis/)workflow-cli`.

I believe we want (release) branches to be created in the latter set of repos as well, or else the `deisrel git tag` command used later on in the release process (which _does_ include the latter set of repos) will fail.

cc @smothiki

**Comment by smothiki** [comment]
There might be a difference in running release checklist steps. I will recheck what exactly caused this. Some repos it failed to create release branch and some like charts already that release branch got merged.

**Comment by arschles** [comment]
If we do continue developing features for this repo, I'd recommend finding a way to remove `additionalGitRepos`

**Comment by smothiki** [comment]
Yeah, might be more specific documentation in the release checklist about additional repos would have helped.

**Comment by vdice** [comment]
Closing as irrelevant (no longer a `branches` command in deisrel)
