### ISSUE TITLE
Shows dockerbuilder as "dirty" although latest tag matches HEAD

### ISSUE THREAD

**Issue by mboersma** [deis/deisrel#125]
Somehow I broke `deisrel`:
```bash
$ deisrel ~/.helmc/workspace/charts/workflow-v2.2.0/tpl/generate_params.toml components.json 
builder         v2.2.0 -> v2.3.0 (dirty)
	builder has unrelased changes. See https://github.com/deis/builder/compare/v2.3.0...master
controller      v2.2.0 -> v2.2.1 (dirty)
	controller has unrelased changes. See https://github.com/deis/controller/compare/v2.2.1...master
database        v2.2.0 -> v2.2.0 (dirty)
	database has unrelased changes. See https://github.com/deis/postgres/compare/v2.2.0...master
dockerbuilder   v2.2.0 -> v2.3.0 (dirty)
	dockerbuilder has unrelased changes. See https://github.com/deis/dockerbuilder/compare/v2.3.0...master
...
```

But dockerbuilder was just tagged as v2.3.0 and there are no newer commits, and visiting the URL above shows "v2.3.0 and master are identical."

This isn't hard to work around for now. Not sure what's going wrong though--other components so far seem to report status correctly.

**Comment by Joshua-Anderson** [comment]
I'll investigate right now.

**Comment by Joshua-Anderson** [comment]
The cause of this is that dockerbuilder is using an annotated tag, unlike the other repositories. Annotated tags have their own SHA, unlike a light tag, which points to a commit. So my comparison of `tag_sha == master_sha` isn't going to work for an annotated tag. I'll add so logic around this.
