### ISSUE TITLE
Extra blank lines in CHANGELOG output

### ISSUE THREAD

**Issue by mboersma** [deis/deisrel#136]
Sometimes a `deisrel changelog individual` command will have extra blank lines in it. For example, if there are no `feat` commits, the header is followed by two blank lines.

This should be cleaned up so the resulting CHANGELOG output can be used directly in scripts or other automation.

**Comment by helgi** [comment]
That's go templating at work

**Comment by Joshua-Anderson** [comment]
huh. I thought I fixed this recently by prepending and appending `-` to get rid of empty lines in the template. I'm pretty sure I got rid of all of them. Are you using the latest version of deisrel?

**Comment by mboersma** [comment]
>  Are you using the latest version of deisrel?

Yes, I just rebuilt it from master. Here's a case where an extra blank line shows up still:

```bash
$ deisrel changelog individual logger unknown
skipping commit 99da2805ec8dcd87dcd508887d7faf5824502a07

Creating changelog for logger with tag v2.3.1 through commit 99da2805ec8dcd87dcd508887d7faf5824502a07

### v2.3.1 -> unknown


#### Maintenance

- [`e36fe0f`](https://github.com/deis/logger/commit/e36fe0f4e0dcafa7376a3fb6c35e597c3c0b3e43) CHANGELOG: remove CHANGELOG
```
