### ISSUE TITLE
Use inline HTML for markdown headers

### ISSUE THREAD

**Issue by mboersma** [deis/deisrel#139]
When creating changelogs, the `#` designating a Markdown header is interpreted by `git` as a comment, and discarded. Instead let's use the underscore format from now on, which should work in all cases.

**Comment by mboersma** [comment]
Actually since the `setext` style only supports H1 and H2 headers, it's going to be easier to just emit inline HTML here.

**Comment by vdice** [comment]
@mboersma shall we close this as we no longer annotate the git release tag?
