### ISSUE TITLE
add --dry-run tag to git tag

### ISSUE THREAD

**Issue by bacongobbler** [deis/deisrel#28]
this will allow us to test this command without actually making changes to the repositories

**Comment by Joshua-Anderson** [comment]
Since we now release components individually, `deisrel` no longer needs support for mass tagging  and it has been removed.

**Comment by bendavidpaz** [comment]
git tag --dry-run would be beneficial for continuous integration with repositories that cannot be embedded.

**Comment by bacongobbler** [comment]
we don't use `git tag` at all, @bendavidpaz. It's just an API call at this point. Are you currently using deisrel for your org?

**Comment by bacongobbler** [comment]
Also do note that there does exist a --dry-run flag for `deisrel release`, so it is available. :)
