### ISSUE TITLE
Create command for tagging repos

### ISSUE THREAD

**Issue by vdice** [deis/deisrel#3]
A new command should be added to set a git tag on each repo. For example:
```
deisrel git tag -shas=shas.txt -tag=v2.0.0-beta2
```
The input file should be the SHA to tag each repo with

**Comment by bacongobbler** [comment]
Is the input file a requirement? For the past releases we've mandated a code freeze and just used the latest SHAs from each repository. We could allow both where if the shas flag isn't present, we fetch the latest, otherwise use what's in shas.txt. Does that seem fair?

**Comment by arschles** [comment]
I'd be ok with being able to select either one. Thoughts on adding a `--latest-shas` flag (and have it be mutually exclusive to the `-shas` flag)?

**Comment by bacongobbler** [comment]
If we implement that, what would be the default behaviour (`deisrel git tag`)?

**Comment by arschles** [comment]
I'd say it should be required to pass the `-shas` flag, so that nobody accidentally tags a bunch of repos on the latest sha when they didn't mean to

**Comment by bacongobbler** [comment]
Okay, so the full UX is

```
$ deisrel git sha <tag>
<usage>
$ deisrel git sha --latest-shas <tag>
<tag with latest shas on each repo>
$ deisrel git sha --sha-file=shas.txt <tag>
<tag each repo with the corresponding shas from shas.txt>
```

How would we format the file? `<key>=<value>` where `key` is the repo and `value` is the sha?
