### ISSUE TITLE
env var needing to be deleted in release chart

### ISSUE THREAD

**Issue by vdice** [deis/deisrel#37]
From release checklist, there is the following manual step:

```
Delete the `KUBERNETES_POD_TERMINATION_GRACE_PERIOD_SECONDS` env var from `workflow-$WORKFLOW_RELEASE_SHORT/tpl/deis-controller-rc.yaml`
```

We should automate this step in `deisrel` -- perhaps after inquiring as to the origins of exactly _why_ it needs to be deleted and whether or not a different approach in chart itself might be a better option...

**Comment by Joshua-Anderson** [comment]
deisrel no longer manages charts, but that step is still there in the release guide.

The controller chart is now using deployments instead of rcs, so I wonder if it's stale.

@helgi any idea?

**Comment by mboersma** [comment]
This still needs to be done in the deis-controller-deployment.rc for Helm classic Chart releases. That step was automated in deis/charts#363 and (un-)documented in deis/workflow#530.
