### ISSUE TITLE
git tag should sort repo list

### ISSUE THREAD

**Issue by jchauncey** [deis/deisrel#38]
makes it hard to know if you've left a repo out or not

**Comment by bacongobbler** [comment]
All the repos should be tagged in parallel so I don't think there is any deterministic way to sort them

**Comment by jchauncey** [comment]
The output before you answer yes is unsorted. And even after if you save
the output into a slice and then sort it that would be a better ux.

**Comment by bacongobbler** [comment]
Ah right! So you want the confirmation list to be sorted. That makes more sense. :)

**Comment by bacongobbler** [comment]
clearing as this is a nice enhancement, but not something we absolutely must get done for rc1.
