### ISSUE TITLE
Makefile: Create commands that dont rely on docker

### ISSUE THREAD

**Issue by jchauncey** [deis/deisrel#40]

**Comment by arschles** [comment]
@jchauncey I'd like to keep the docker-based operations but suffix the build targets with `-docker`. this way, we can still use them in CI (not strictly necessary, but we can make that change later, in another issue). here's the list of applicable targets:

- `build`
- `build-docker`
- `test`
- `test-docker`

thoughts?

**Comment by jchauncey** [comment]
Yeah as long as we have a way to not run them in docker that's fine

**Comment by bacongobbler** [comment]
clearing the milestone as this is a nice-to-have but not required for rc1
