### ISSUE TITLE
[proposal] refactor helm-params,stage

### ISSUE THREAD

**Issue by vdice** [deis/deisrel#52]
<h3>Current State<h3>

The current `deisrel` workflow for generating all of a given release chart's files needing updating (inserting `$WORKFLOW_RELEASE(_SHORT)` where necessary, inserting latest git sha values for component `dockerTag` values, etc.) can be seen in the current version of the [Release Checklist](https://github.com/deis/workflow/blob/master/src/roadmap/release-checklist.md#step-1-create-new-helm-classic-charts).  For instance, it looks something like:

Stage copies of the tpl/generate_params.toml for each chart into staging. deisrel will automatically populate the latest commit sha values for each component's dockerTag:
```
deisrel helm-params --stage workflow
deisrel helm-params --stage e2e
```
Stage copies of the additional files in workflow-dev(-e2e) charts needing release value updates into staging (i.e., Chart.yaml, README.md, etc.)
```
deisrel helm-stage workflow
deisrel helm-stage e2e
```
Copy these staged files back to the correlating chart directories created in step 2 above:
```
cp -r staging/workflow-dev/* workflow-$WORKFLOW_RELEASE_SHORT
cp -r staging/workflow-dev-e2e/* workflow-$WORKFLOW_RELEASE_SHORT-e2e

```
<h3>Proposed State<h3>

I propose we reduce the number of `deisrel`/associated command invocations.  I'd like to see the above workflow change to something like:

Stage all release-updated files for each (workflow, e2e) chart into the newly created release chart dirs:
```
deisrel helm-stage --stagedir workflow-$WORKFLOW_RELEASE_SHORT workflow
deisrel helm-stage --stagedir workflow-$WORKFLOW_RELEASE_SHORT-e2e e2e
```

Which would generate all necessary files for each chart and output them directly into supplied `--stagedir`.  If not supplied, it would default to throwing files into local `staging` dir as before.

**Comment by arschles** [comment]
:+1: on the idea of consolidating all of the helm chart related functionality into a single command

**Comment by arschles** [comment]
@vdice why close this?
