### ISSUE TITLE
Stage charts for standalone components

### ISSUE THREAD

**Issue by krancour** [deis/deisrel#71]
Some components (e.g. router) can be used without the rest of Workflow. We should update deisrel to generate new charts for said components in addition to the new Workflow charts.

**Comment by sgoings** [comment]
Removing 2.0-rc2 milestone assignment because this doesn't need to be done for rc2.

**Comment by krancour** [comment]
When would we want this done for? Are the standalone charts not part of the upcoming release?

**Comment by krancour** [comment]
This was addressed by #73. Closing.
