### ISSUE TITLE
Limit cross-compilation to just darwin/amd64 and linux/amd64

### ISSUE THREAD

**Issue by krancour** [deis/deisrel#94]
These two combinations should sufficiently cover anyone who might actually coordinate a release of Workflow (i.e. the deis team). There's no reason to build all the other os/arch permutations and allow them to take up space in GCS if they will never be used.

**Comment by bacongobbler** [comment]
@jchauncey mentioned something about releasing from his raspberry pi (:trollface:), but I would agree if we're trying to cut down on space/wasted $$$.

**Comment by krancour** [comment]
We can add arm in later if he was serious.

**Comment by arschles** [comment]
Thoughts on also building for 32 bit architectures?

**Comment by krancour** [comment]
@arschles is anyone who might actually coordinate a release using such a machine?

**Comment by arschles** [comment]
no, not right this moment
