### ISSUE TITLE
git release branch creation

### ISSUE THREAD

**Issue by vdice** [deis/deisrel#96]
As of this writing, our release process includes [pushing release branches](http://docs-v2.readthedocs.io/en/latest/roadmap/release-checklist/#step-1-cut-repo-branches-and-push-image-tags) to all component and/or Workflow-related repos.  Currently, this is done from [sgoings/deis-workflow-group](https://github.com/sgoings/deis-workflow-group), but we intend to discontinue use of this tool once the functionality exists here.

Therefore, this ticket is for implementing the functionality mentioned in [Step 1.1](https://github.com/sgoings/deis-workflow-group) of the Release Checklist.

**Comment by Joshua-Anderson** [comment]
Our release process no longer involves release branches, so deisrel no longer needs to handle this.
